apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ayunet-backend-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  tls:
    - hosts:
        - api.ayunet.org
      secretName: ayunet-tls-secret
  rules:
    - host: api.ayunet.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ayunet-backend-service
                port:
                  number: 4000
