export const ROUTES = {
  PUBLIC: {
    HOME: '/',
    LOGIN: '/login',
    REGISTER: '/register',
    FORGOT_PASSWORD: '/forgot-password',
    RESET_PASSWORD: '/reset-password',
    UNAUTHORIZED: '/403',
    NOT_FOUND: '/404',
    SERVER_ERROR: '/500',
    OFFLINE: '/offline',
  },
  ADMIN: {
    DASHBOARD: '/admin/dashboard',
    HOSPITALS: '/admin/hospitals',
    USERS: '/admin/users',
    ROLES: '/admin/roles',
    REPORTS: '/admin/reports',
    SYSTEM_LOGS: '/admin/logs',
    TENANT_SETTINGS: '/admin/settings/tenant',
    WHITE_LABEL: '/admin/settings/white-label',
  },
  DOCTOR: {
    DASHBOARD: '/doctor/dashboard',
    APPOINTMENTS: '/doctor/appointments',
    PATIENTS: '/doctor/patients',
    EMR: '/doctor/emr',
    PRESCRIPTIONS: '/doctor/prescriptions',
    AI_ASSISTANT: '/doctor/ai-assistant',
  },
  RECEPTION: {
    DASHBOARD: '/reception/dashboard',
    QUEUE: '/reception/queue',
    APPOINTMENTS: '/reception/appointments',
    CHECK_IN: '/reception/check-in',
    PATIENT_REGISTRATION: '/reception/patient-registration',
  },
  LABORATORY: {
    DASHBOARD: '/lab/dashboard',
    ORDERS: '/lab/orders',
    SAMPLE_COLLECTION: '/lab/samples',
    REPORTS: '/lab/reports',
  },
  PHARMACY: {
    DASHBOARD: '/pharmacy/dashboard',
    PRESCRIPTIONS: '/pharmacy/prescriptions',
    DISPENSE: '/pharmacy/dispense',
    INVENTORY: '/pharmacy/inventory',
  },
  PATIENT: {
    DASHBOARD: '/patient/dashboard',
    APPOINTMENTS: '/patient/appointments',
    MEDICAL_RECORDS: '/patient/records',
    PRESCRIPTIONS: '/patient/prescriptions',
    INVOICES: '/patient/invoices',
    AI_BOT: '/patient/ai-bot',
  },
};
